export type TechnicalPage = {
  category: "servicios" | "ingenieria";
  slug: string;
  title: string;
  description: string;
  sections: { title: string; text: string }[];
  checklist: string[];
  related: string[];
};

type Seed = Omit<TechnicalPage, "sections" | "checklist" | "related"> & {
  system: string;
  planning: string;
  control: string;
};

const seeds: Seed[] = [
  {category:"servicios",slug:"montaje-puentes",title:"Montaje de puentes prefabricados",description:"Planificación de vigas, tableros y elementos prefabricados para puentes.",system:"vigas, tableros, prelosas, apoyos y diafragmas, considerando la luz, el peso de cada pieza y la geometría del vano",planning:"posiciones de grúa, cortes o afecciones al tráfico, accesos a estribos y pilas, orden de llegada y estados intermedios del tablero",control:"cotas de apoyo, alineación, nivelación, entrega de cargas, arriostramiento y condiciones para liberar el gancho"},
  {category:"servicios",slug:"montaje-viaductos",title:"Montaje de viaductos prefabricados",description:"Secuencias repetitivas y logística de elementos prefabricados en viaductos.",system:"vigas y elementos de tablero distribuidos en varios vanos, con pesos, longitudes y radios de trabajo que pueden variar entre pilas",planning:"avance por vanos, plataformas de posicionamiento, continuidad del suministro, cambios de configuración y compatibilidad con otras actividades",control:"identificación de piezas, apoyos, separación entre vigas, estabilidad transversal y repetición de controles en cada ciclo"},
  {category:"servicios",slug:"montaje-paneles-prefabricados",title:"Montaje de paneles prefabricados",description:"Manipulación y colocación de paneles de hormigón y otros sistemas prefabricados.",system:"paneles horizontales o verticales, puntos de izado, geometría, acabado, centro de gravedad y elementos de conexión previstos",planning:"orden de descarga, orientación en transporte, espacio para volteo, posición de montaje y permanencia de los apeos temporales",control:"aplome, juntas, cotas, fijaciones, protección de aristas y estabilidad antes de retirar útiles o arriostramientos"},
  {category:"servicios",slug:"montaje-fachadas-prefabricadas",title:"Montaje de fachadas prefabricadas",description:"Coordinación de paneles de fachada, cerramientos y sus fijaciones.",system:"paneles arquitectónicos, cerramientos, subestructuras, anclajes y juntas cuya tolerancia conjunta condiciona el resultado de fachada",planning:"secuencia por paños, accesibilidad de plataformas, descarga, orientación de piezas, protección de acabados y coordinación con estructura",control:"alineación, aplome, ancho de junta, posición de anclajes, fijación temporal y compatibilidad con sellados posteriores"},
  {category:"servicios",slug:"montaje-estructuras-metalicas",title:"Montaje de estructuras metálicas",description:"Secuencia de pilares, vigas, cerchas y arriostramientos metálicos.",system:"pilares, vigas, cerchas, correas, uniones atornilladas o soldadas y arriostramientos que forman el camino resistente",planning:"módulos de montaje, preensamblajes, alcance de equipos, plataformas de trabajo, orden de uniones y estabilidad de cada fase",control:"ejes, cotas, verticalidad, apriete o ejecución de uniones, arriostramientos y liberación progresiva de medios temporales"},
  {category:"servicios",slug:"montaje-naves-industriales",title:"Montaje de naves industriales",description:"Montaje coordinado de estructura, cubierta y cerramientos de naves.",system:"pilares, vigas, cerchas, elementos de cubierta, paneles y cerramientos de hormigón, acero o sistemas combinados",planning:"avance por crujías, suministro por lotes, circulación interior, radios de trabajo, plataformas y compatibilidad entre oficios",control:"replanteo, estabilidad longitudinal y transversal, geometría de crujías, apoyos, uniones y tolerancias acumuladas"},
  {category:"servicios",slug:"montaje-edificios-prefabricados",title:"Montaje de edificios prefabricados",description:"Secuencia estructural para edificios ejecutados con elementos prefabricados.",system:"pilares, vigas, paneles portantes, losas, escaleras y núcleos que deben trabajar juntos desde estados provisionales",planning:"avance por plantas o sectores, entrega de piezas, huecos, bordes, apeos, uniones húmedas o secas y acceso de equipos",control:"cotas de planta, apoyos, verticalidad, juntas, continuidad estructural y condiciones previas a cargar niveles montados"},
  {category:"servicios",slug:"montaje-prefabricados-hormigon",title:"Montaje de prefabricados de hormigón",description:"Criterios comunes para piezas estructurales y arquitectónicas de hormigón prefabricado.",system:"elementos pesados con geometría, insertos, puntos de izado, apoyos y tolerancias definidos desde fabricación y proyecto",planning:"recepción, identificación, manipulación, radio de montaje, útiles compatibles, secuencia de apoyos y estabilidad provisional",control:"estado de piezas e insertos, asiento, nivel, aplome, uniones, rellenos y autorización para retirar sujeciones temporales"},
  {category:"ingenieria",slug:"ingenieria-montaje",title:"Ingeniería de montaje",description:"Conversión del proyecto en una secuencia de obra ejecutable y verificable.",system:"información de proyecto, fabricante, transportista, equipos de elevación, medios auxiliares y condiciones reales del emplazamiento",planning:"hipótesis, posiciones, fases, responsables, interferencias, límites de uso y puntos en los que una desviación obliga a revisar",control:"vigencia de documentos, trazabilidad de datos, comprobaciones previas, aceptación de cambios y registro del resultado"},
  {category:"ingenieria",slug:"planes-izado",title:"Planes de izado",description:"Datos, comprobaciones y comunicación necesarios para definir un izado.",system:"pieza, aparejos, accesorios, equipo de elevación, configuración, radio, altura, terreno y entorno de la maniobra",planning:"trayectoria desde recogida hasta posición final, capacidades disponibles, apoyos, obstáculos, zona de exclusión y comunicaciones",control:"identidad y peso de la carga, útiles, configuración, condiciones del terreno, viento, responsables y criterios de parada"},
  {category:"ingenieria",slug:"gruas-montaje",title:"Grúas para montaje de prefabricados",description:"Selección de equipos según carga, radio, altura, configuración y emplazamiento.",system:"grúas móviles o equipos adecuados al peso total suspendido y al radio real, no únicamente al tonelaje nominal del modelo",planning:"configuración de pluma y contrapeso, estabilizadores, presión sobre apoyos, montaje del equipo, acceso y cambios de posición",control:"tabla de cargas aplicable, limitaciones del fabricante, nivelación, entorno, accesorios y correspondencia con el plan comunicado"},
  {category:"ingenieria",slug:"transporte-especial",title:"Transporte especial para prefabricados",description:"Integración del transporte, la descarga y el ritmo de montaje.",system:"vehículos, piezas de gran longitud o masa, apoyos de transporte, amarres, rutas, accesos y restricciones administrativas",planning:"orden de expedición, horarios, permisos aplicables, radios de giro, esperas, zona de descarga y retorno de vehículos",control:"identificación y orientación de piezas, estado visible, liberación de amarres, coordinación con izado y ausencia de bloqueos"},
  {category:"ingenieria",slug:"seguridad-montaje",title:"Seguridad en el montaje de prefabricados",description:"Integración preventiva de personas, equipos, cargas suspendidas y estados temporales.",system:"tareas, equipos, zonas de trabajo, accesos, bordes, cargas suspendidas y condiciones cambiantes que deben coordinarse",planning:"responsables, comunicaciones, zonas de exclusión, protecciones, rescate, criterios de parada y respuesta ante desviaciones",control:"autorizaciones, inspecciones, condiciones ambientales, comportamiento del terreno, cumplimiento de la secuencia y reporte de incidencias"},
  {category:"ingenieria",slug:"control-geometrico",title:"Control geométrico del montaje",description:"Replanteo y comprobación de ejes, cotas, apoyos, aplome y tolerancias.",system:"red de referencia, ejes, niveles, puntos de apoyo, geometría de piezas y tolerancias de fabricación, obra y montaje",planning:"instrumentos, puntos y momentos de medida, responsables, registro, criterios de aceptación y tratamiento de acumulaciones",control:"calibración o verificación del equipo, estabilidad de referencias, medidas antes y después de fijar y trazabilidad de correcciones"},
  {category:"ingenieria",slug:"secuencia-montaje",title:"Secuencia de montaje",description:"Orden técnico y logístico para mantener estabilidad, acceso y continuidad de obra.",system:"piezas, uniones, apoyos, arriostramientos, equipos, transporte y actividades cuya dependencia determina el orden posible",planning:"estados intermedios, sentido de avance, lotes de suministro, cambios de posición, puntos de espera y alternativas autorizadas",control:"prerrequisitos de cada paso, estabilidad alcanzada, fijaciones ejecutadas, espacio libre y autorización para continuar"},
];

const specifics:Record<string,{titles:[string,string,string];risk:string;related:string[]}>= {
  "montaje-puentes":{titles:["Elementos y condicionantes del vano","Decisiones antes de ocupar la zona de trabajo","Apoyos y estabilidad del tablero"],risk:"Un cambio de radio, una cota de apoyo incorrecta o la falta de estabilidad transversal puede invalidar la maniobra prevista y afectar al siguiente elemento.",related:["/ingenieria/planes-izado","/ingenieria/control-geometrico","/ingenieria/transporte-especial"]},
  "montaje-viaductos":{titles:["Lectura del viaducto por vanos","Ciclo de suministro e izado","Repetición sin acumular desviaciones"],risk:"La repetición no elimina el riesgo: cambios entre plataformas, piezas o radios exigen comprobar de nuevo la capacidad y la geometría de cada ciclo.",related:["/servicios/montaje-puentes","/ingenieria/secuencia-montaje","/ingenieria/control-geometrico"]},
  "montaje-paneles-prefabricados":{titles:["Geometría, acabado y centro de gravedad","Descarga, volteo y presentación","Aplome y sujeción provisional"],risk:"Liberar el panel antes de completar su fijación temporal o utilizar puntos no previstos puede producir giros, daños en aristas y pérdida de estabilidad.",related:["/servicios/montaje-fachadas-prefabricadas","/ingenieria/planes-izado","/ingenieria/seguridad-montaje"]},
  "montaje-fachadas-prefabricadas":{titles:["Fachada, estructura y tolerancias","Secuencia por paños","Anclajes, juntas y acabado"],risk:"Las tolerancias acumuladas entre estructura, panel y anclaje pueden impedir la colocación o trasladar errores a juntas y piezas posteriores.",related:["/servicios/montaje-paneles-prefabricados","/ingenieria/control-geometrico","/ingenieria/secuencia-montaje"]},
  "montaje-estructuras-metalicas":{titles:["Camino resistente del conjunto","Módulos, uniones y medios auxiliares","Geometría y arriostramiento"],risk:"Una estructura parcialmente montada puede carecer de la rigidez del modelo final; retirar arriostramientos o equipos antes de tiempo cambia su comportamiento.",related:["/servicios/montaje-naves-industriales","/ingenieria/secuencia-montaje","/ingenieria/seguridad-montaje"]},
  "montaje-naves-industriales":{titles:["Sistema estructural y cerramientos","Avance coordinado por crujías","Tolerancias del conjunto"],risk:"Cerrar una crujía o cargar elementos secundarios sin estabilizar la estructura principal puede dificultar correcciones y crear estados no previstos.",related:["/servicios/montaje-estructuras-metalicas","/servicios/montaje-paneles-prefabricados","/ingenieria/secuencia-montaje"]},
  "montaje-edificios-prefabricados":{titles:["Elementos portantes y plantas","Orden de cierre estructural","Continuidad y carga de niveles"],risk:"El estado provisional de una planta no equivale al edificio terminado; apeos, uniones y restricciones de carga deben mantenerse hasta cumplir sus condiciones.",related:["/servicios/montaje-prefabricados-hormigon","/ingenieria/control-geometrico","/ingenieria/secuencia-montaje"]},
  "montaje-prefabricados-hormigon":{titles:["Pieza, insertos y apoyos","De fabricación a posición final","Asiento, unión y liberación"],risk:"Daños en insertos, apoyos incompletos o útiles incompatibles alteran cómo se introduce la carga y requieren detener la operación para su revisión.",related:["/servicios/montaje-edificios-prefabricados","/ingenieria/planes-izado","/ingenieria/control-geometrico"]},
  "ingenieria-montaje":{titles:["Información que gobierna el montaje","Hipótesis y decisiones documentadas","Gestión técnica de los cambios"],risk:"Una hipótesis no identificada puede convertirse en una instrucción errónea en obra; cada límite debe quedar visible para quien prepara y ejecuta.",related:["/ingenieria/planes-izado","/ingenieria/secuencia-montaje","/ingenieria/control-geometrico"]},
  "planes-izado":{titles:["Carga total y equipo","Trayectoria y entorno de la maniobra","Comprobación previa al izado"],risk:"El peso nominal de la pieza no incluye necesariamente aparejos y accesorios; omitirlos o medir mal el radio reduce el margen disponible.",related:["/ingenieria/gruas-montaje","/ingenieria/seguridad-montaje","/ingenieria/secuencia-montaje"]},
  "gruas-montaje":{titles:["Capacidad útil, no tonelaje nominal","Configuración y apoyo del equipo","Correspondencia entre estudio y obra"],risk:"Seleccionar por la denominación comercial de la grúa ignora radio, longitud de pluma, contrapeso y configuración, que determinan la capacidad real.",related:["/ingenieria/planes-izado","/ingenieria/seguridad-montaje","/ingenieria/transporte-especial"]},
  "transporte-especial":{titles:["La pieza durante el transporte","Ruta, acceso y orden de llegada","Transferencia segura a la descarga"],risk:"Una pieza que llega fuera de secuencia u orientada en sentido incompatible puede exigir esperas, maniobras adicionales o bloquear el acceso de otros vehículos.",related:["/ingenieria/secuencia-montaje","/ingenieria/planes-izado","/servicios/montaje-puentes"]},
  "seguridad-montaje":{titles:["Riesgos del estado provisional","Organización y criterios de parada","Verificación antes de continuar"],risk:"La presión por mantener el ritmo nunca convierte una desviación en aceptable; pérdida de comunicación, acceso a zona excluida o cambio ambiental exige parar y revisar.",related:["/ingenieria/planes-izado","/ingenieria/secuencia-montaje","/ingenieria/gruas-montaje"]},
  "control-geometrico":{titles:["Referencias y tolerancias","Cuándo y cómo medir","Correcciones con trazabilidad"],risk:"Medir desde referencias inestables o corregir una pieza sin considerar la acumulación puede trasladar el error a todo un paño, vano o crujía.",related:["/ingenieria/secuencia-montaje","/servicios/montaje-fachadas-prefabricadas","/servicios/montaje-puentes"]},
  "secuencia-montaje":{titles:["Dependencias entre piezas y medios","Estados intermedios y puntos de espera","Cambios de orden en obra"],risk:"Alterar el orden para resolver una demora puede eliminar un arriostramiento, un acceso o una referencia necesarios para las operaciones posteriores.",related:["/ingenieria/seguridad-montaje","/ingenieria/transporte-especial","/ingenieria/control-geometrico"]},
};

const makeSections = (seed: Seed) => {const detail=specifics[seed.slug];return [
  {title:detail.titles[0],text:`El análisis comienza con ${seed.system}. No todos los datos tienen el mismo efecto: geometría, masa, apoyos y condiciones reales determinan qué solución puede estudiarse. ${detail.risk}`},
  {title:detail.titles[1],text:`Antes de ejecutar se deciden ${seed.planning}. La secuencia debe indicar sus prerrequisitos y límites para que transporte, señalización, equipo y montaje trabajen con la misma referencia.`},
  {title:detail.titles[2],text:`La aceptación se apoya en ${seed.control}. Si una comprobación no coincide con lo previsto, se registra la desviación, se evalúa su efecto concreto y se valida la alternativa antes de pasar al siguiente estado.`},
]};

export const technicalPages: TechnicalPage[] = seeds.map((seed) => ({
  ...seed,
  sections: makeSections(seed),
  checklist: [`Confirmar ${seed.system}.`, `Definir ${seed.planning}.`, `Comprobar ${seed.control}.`, `Registrar el efecto de cualquier cambio sobre ${specifics[seed.slug].titles[2].toLowerCase()}.`],
  related: specifics[seed.slug].related,
}));

export function getTechnicalPage(category:string,slug:string){return technicalPages.find(page=>page.category===category&&page.slug===slug)}
