import {NextResponse} from "next/server";
import {Resend} from "resend";
import {createProductInquiry} from "@/lib/catalog-db";
import {sanitizeText} from "@/lib/prestudy";
import {validateProductInquiry,type ProductInquiryInput} from "@/lib/product-inquiry";

const attempts=new Map<string,{count:number;reset:number}>();
function limited(request:Request){const key=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"local",now=Date.now(),current=attempts.get(key);if(!current||current.reset<now){attempts.set(key,{count:1,reset:now+15*60_000});return false;}current.count++;return current.count>8;}
const ref=()=>`MP-TIENDA-${new Date().getFullYear()}-${crypto.randomUUID().replace(/-/g,"").slice(0,6).toUpperCase()}`;
export async function POST(request:Request){if(limited(request))return NextResponse.json({ok:false,error:"Demasiadas solicitudes. Inténtalo más tarde."},{status:429});try{const raw=await request.json() as ProductInquiryInput;if(raw.website)return NextResponse.json({ok:true,reference:ref()});const errors=validateProductInquiry(raw);if(Object.keys(errors).length)return NextResponse.json({ok:false,error:Object.values(errors)[0]},{status:400});const id=ref();const clean={id,kind:raw.kind,productId:sanitizeText(raw.productId,120),productName:sanitizeText(raw.productName,200),name:sanitizeText(raw.name,120),company:sanitizeText(raw.company,160),email:sanitizeText(raw.email,200),phone:sanitizeText(raw.phone,80),message:sanitizeText(raw.message,4000),documents:raw.documents};await createProductInquiry(clean);if(!process.env.RESEND_API_KEY)throw new Error("El servicio de correo no está configurado.");const resend=new Resend(process.env.RESEND_API_KEY),from=process.env.MAIL_FROM||"Montaje Prefabricado <ofertas@montajesprefabricados.com>",to=process.env.MAIL_TO||"ofertas@montajesprefabricados.com";const files=clean.documents.length?`<h3>Archivos adjuntos</h3><ul>${clean.documents.map(item=>`<li><a href="${item.url}">${sanitizeText(item.name,200)}</a></li>`).join("")}</ul>`:"";const result=await resend.emails.send({from,to,replyTo:clean.email||undefined,subject:`${id} · ${clean.productName||"Búsqueda asistida"}`,html:`<h1>Nueva solicitud de tienda</h1><p><b>Referencia:</b> ${id}</p><p><b>Tipo:</b> ${clean.kind}</p><p><b>Producto:</b> ${clean.productName||"No identificado"} (${clean.productId||"—"})</p><p><b>Cliente:</b> ${clean.name} · ${clean.company||"Sin empresa"}</p><p><b>Email:</b> ${clean.email||"—"} · <b>Teléfono:</b> ${clean.phone||"—"}</p><h3>Solicitud</h3><p>${clean.message.replace(/\n/g,"<br>")}</p>${files}`});if(result.error)throw new Error(result.error.message);if(clean.email){const confirmation=await resend.emails.send({from,to:clean.email,subject:`Solicitud recibida · ${id}`,html:`<h1>Hemos recibido tu solicitud</h1><p>Hola ${clean.name},</p><p>Hemos registrado tu petición sobre <b>${clean.productName||"un producto del catálogo"}</b>.</p><p><b>Referencia:</b> ${id}</p><p>La documentación o respuesta se enviará a este mismo correo cuando se incorpore al expediente. No necesitas contactar tú al fabricante.</p><p>Montaje Prefabricado · +34 624 473 123</p>`});if(confirmation.error)console.error("[/api/product-inquiries confirmation]",confirmation.error);}return NextResponse.json({ok:true,reference:id});}catch(cause){console.error("[/api/product-inquiries]",cause);return NextResponse.json({ok:false,error:cause instanceof Error?cause.message:"No se pudo registrar la solicitud."},{status:500});}}
