import Image from "next/image";
import Link from "next/link";
import type { SeoPage } from "@/data/seo-pages";
import { seoPageByPath } from "@/data/seo-pages";
import { buildPageSchemas } from "@/lib/seo";
import Footer from "./Footer";
import Header from "./Header";
import SeoJsonLd from "./SeoJsonLd";

const groupLabel = { service: "Servicios", type: "Tipologías", location: "Ubicaciones" } as const;

export default function SeoLandingPage({ page }: { page: SeoPage }) {
  return <div className="v21-home service-page"><SeoJsonLd schemas={buildPageSchemas(page)} /><div className="service-mast"><Image src={page.image} alt={page.h1} fill priority sizes="100vw" /><div className="service-overlay"/><Header/><div className="shell service-hero"><nav aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><span>{groupLabel[page.kind]}</span><span>/</span><span aria-current="page">{page.h1}</span></nav><div className="kicker mono">{page.eyebrow}</div><h1>{page.h1}</h1><p>{page.description}</p><div className="hero-actions"><Link className="v21-btn redbtn" href="/#preestudio">Solicitar preestudio →</Link>{page.path!=="/servicios/lifting-plan"&&<Link className="v21-btn lightbtn" href="/servicios/lifting-plan">Preparar un lifting plan</Link>}</div></div></div><main><section className="v21-section"><div className="shell service-intro"><div className="kicker mono">Criterio técnico</div><p>{page.intro}</p></div></section><section className="v21-section service-sections"><div className="shell"><div className="section-head"><div><div className="kicker mono">Alcance</div><h2>Qué debe definirse<br/><span className="red">antes de ejecutar.</span></h2></div></div><div className="service-detail-grid">{page.sections.map((section,index)=><article key={section.title}><span className="mono">{String(index+1).padStart(2,"0")}</span><h2>{section.title}</h2><p>{section.body}</p><ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></div></section><section className="v21-section seo-faq"><div className="shell"><div className="section-head"><div><div className="kicker mono">Preguntas frecuentes</div><h2>Decisiones<br/><span className="red">antes del montaje.</span></h2></div><p>Respuestas basadas en la información que debe comprobarse para preparar una operación.</p></div><div className="seo-faq-grid">{page.faqs.map(faq=><article key={faq.question}><h3>{faq.question}</h3><p>{faq.answer}</p></article>)}</div></div></section><section className="v21-section dark"><div className="shell"><div className="section-head"><div><div className="kicker mono">Enlaces relacionados</div><h2>Completa el<br/><span className="red">contexto técnico.</span></h2></div></div><div className="related-services">{page.related.map(path=>{const related=seoPageByPath[path];return related?<Link href={path} key={path}><strong>{related.h1}</strong><span>{related.description}</span><b>Ver página →</b></Link>:null})}</div><div className="service-cta"><h2>¿Tienes planos, pesos y una ubicación?</h2><p>Comparte la información disponible. El preestudio identificará los datos pendientes antes de definir medios y secuencia.</p><Link className="v21-btn redbtn" href="/#preestudio">Iniciar preestudio →</Link></div></div></section></main><Footer/></div>;
}
