import Image from "next/image";
import Link from "next/link";
import type { TechnicalService } from "@/data/technical-services";
import { technicalServiceBySlug } from "@/data/technical-services";
import Header from "./Header";
import Footer from "./Footer";

export default function TechnicalServicePage({service}:{service:TechnicalService}) {
  return <div className="v21-home service-page"><div className="service-mast"><Image src={service.image} alt="" fill priority sizes="100vw" /><div className="service-overlay"/><Header/><div className="shell service-hero"><nav aria-label="Migas de pan"><Link href="/">Inicio</Link><span>/</span><span>Servicios</span><span>/</span><span aria-current="page">{service.title}</span></nav><div className="kicker mono">{service.eyebrow}</div><h1>{service.title}</h1><p>{service.description}</p><div className="hero-actions"><Link className="v21-btn redbtn" href="/#preestudio">Solicitar preestudio →</Link>{service.slug!=="lifting-plan"&&<Link className="v21-btn lightbtn" href="/servicios/lifting-plan">Lifting plan</Link>}</div></div></div><main><section className="v21-section"><div className="shell service-intro"><div className="kicker mono">Criterio técnico</div><p>{service.intro}</p></div></section><section className="v21-section service-sections"><div className="shell"><div className="section-head"><div><div className="kicker mono">Alcance</div><h2>Qué se estudia<br/><span className="red">antes de ejecutar.</span></h2></div></div><div className="service-detail-grid">{service.sections.map((section,index)=><article key={section.title}><span className="mono">{String(index+1).padStart(2,"0")}</span><h2>{section.title}</h2><p>{section.body}</p><ul>{section.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></div></section><section className="v21-section dark"><div className="shell deliverable-grid"><div><div className="kicker mono">Resultado</div><h2>Entregables<br/>y decisiones.</h2></div><ul>{service.deliverables.map(item=><li key={item}>{item}</li>)}</ul></div></section><section className="v21-section"><div className="shell"><div className="kicker mono">Servicios relacionados</div><div className="related-services">{service.related.map(slug=>{const related=technicalServiceBySlug[slug];return <Link href={`/servicios/${slug}`} key={slug}><strong>{related.title}</strong><span>{related.description}</span><b>Ver servicio →</b></Link>})}</div><div className="service-cta"><h2>¿Necesitas estudiar una operación concreta?</h2><p>Comparte planos, piezas, ubicación y restricciones. Los datos pendientes pueden identificarse durante la revisión.</p><Link className="v21-btn redbtn" href="/#preestudio">Iniciar preestudio →</Link></div></div></section></main><Footer/></div>;
}
