"use client";
import {useEffect,useMemo,useState} from "react";
import {catalogProducts,type CatalogProduct} from "@/data/catalog";
import {calculatePrice} from "@/lib/pricing";
import PriceAudit from "./PriceAudit";

type Override=Partial<CatalogProduct["commercial"]>;type Overrides=Record<string,Override>;
const storageKey="mp-admin-catalog-v1";const euro=(n:number)=>n.toLocaleString("es-ES",{style:"currency",currency:"EUR"});

export default function CatalogAdmin(){
 const [tab,setTab]=useState<"catalogo"|"proveedores"|"bandeja">("catalogo");
 const [query,setQuery]=useState("");const [material,setMaterial]=useState("todos");const [family,setFamily]=useState("todos");
 const [selectedId,setSelectedId]=useState(catalogProducts[0].id);const [overrides,setOverrides]=useState<Overrides>({});
 useEffect(()=>{try{setOverrides(JSON.parse(localStorage.getItem(storageKey)||"{}"))}catch{}},[]);
 const update=(id:string,patch:Override)=>setOverrides(current=>{const next={...current,[id]:{...current[id],...patch}};localStorage.setItem(storageKey,JSON.stringify(next));return next});
 const rows=useMemo(()=>catalogProducts.map(product=>{const commercial={...product.commercial,...overrides[product.id]};return {...product,commercial,calculated:calculatePrice(commercial)}}),[overrides]);
 const families=Array.from(new Set(rows.map(p=>p.family))).sort();
 const filtered=rows.filter(p=>`${p.sku} ${p.name} ${p.brand} ${p.family}`.toLowerCase().includes(query.toLowerCase())&&(material==="todos"||p.segments.includes(material as never))&&(family==="todos"||p.family===family));
 const selected=rows.find(p=>p.id===selectedId)||rows[0];
 return <div className="admin-shell"><AdminNav tab={tab} setTab={setTab}/><main className="admin-main"><header><div><span className="admin-kicker">CENTRO DE CONTROL</span><h1>{tab==="catalogo"?"Catálogo y rentabilidad":tab==="proveedores"?"Proveedores y fuentes":"Bandeja operativa"}</h1></div><span className="admin-user">Administrador <b>A</b></span></header>
 {tab==="catalogo"&&<><Stats rows={rows}/><section className="admin-work"><div className="admin-list"><div className="admin-tools admin-filter-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar SKU, producto o marca"/><label><span>Material / sistema</span><select value={material} onChange={e=>setMaterial(e.target.value)}><option value="todos">Todos</option><option value="hormigon">Hormigón</option><option value="acero">Acero</option><option value="madera">Madera</option><option value="pvc">Plástico / PVC</option><option value="altura">Trabajos en altura</option><option value="epi">EPI</option></select></label><label><span>Tipo de producto</span><select value={family} onChange={e=>setFamily(e.target.value)}><option value="todos">Todos</option>{families.map(value=><option value={value} key={value}>{value}</option>)}</select></label></div><ProductTable products={filtered} selectedId={selectedId} onSelect={setSelectedId}/></div><ProductEditor product={selected} update={update}/></section></>}
 {tab==="proveedores"&&<><PriceAudit/><ProviderView/></>}{tab==="bandeja"&&<InboxView/>}</main></div>;
}
function AdminNav({tab,setTab}:{tab:string;setTab:(tab:"catalogo"|"proveedores"|"bandeja")=>void}){return <aside className="admin-side"><a href="/" className="admin-brand"><b>MP</b><span>Administración<br/><small>COMERCIAL · PREVIEW</small></span></a><nav><button className={tab==="catalogo"?"active":""} onClick={()=>setTab("catalogo")}>▦ Catálogo</button><button className={tab==="proveedores"?"active":""} onClick={()=>setTab("proveedores")}>⌂ Proveedores y precios</button><button className={tab==="bandeja"?"active":""} onClick={()=>setTab("bandeja")}>✉ Bandeja operativa <i>3</i></button></nav><div className="admin-warning"><strong>ENTORNO PREVIEW</strong><span>Datos guardados en este navegador. Falta autenticación y base de datos antes de producción.</span></div><a className="back-store" href="/tienda">← Ver tienda</a></aside>}
function Stats({rows}:{rows:Array<CatalogProduct&{calculated:ReturnType<typeof calculatePrice>}>}){return <section className="admin-stats"><Stat label="Referencias" value={String(rows.length)} note="en auditoría"/><Stat label="Listas para publicar" value={String(rows.filter(p=>p.commercial.status==="ready").length)} note="requieren expediente completo"/><Stat label="Costes sin verificar" value={String(rows.filter(p=>!p.commercial.costVerified).length)} note="no vinculantes" alert/><Stat label="Comparadas" value={String(rows.filter(p=>p.offers.length===3).length)} note="tres precios del mismo SKU"/></section>}
function Stat({label,value,note,alert}:{label:string;value:string;note:string;alert?:boolean}){return <article className={alert?"alert":""}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Status({value}:{value:string}){return <span className={`status ${value}`}>{value==="ready"?"Publicable":value==="quote"?"Bajo oferta":"Borrador"}</span>}
function ProductTable({products,selectedId,onSelect}:{products:ReturnType<typeof adminRows>;selectedId:string;onSelect:(id:string)=>void}){return <div className="table-wrap"><table><thead><tr><th>Producto</th><th>Coste</th><th>Venta neta</th><th>Margen</th><th>Estado</th></tr></thead><tbody>{products.map(p=><tr key={p.id} onClick={()=>onSelect(p.id)} className={selectedId===p.id?"selected":""}><td><b>{p.name}</b><small>{p.sku} · {p.family}</small></td><td>{p.commercial.cost?euro(p.commercial.cost):"Pendiente"}</td><td><b>{p.calculated.salePriceNet?euro(p.calculated.salePriceNet):"Pendiente"}</b></td><td>{p.calculated.actualMarginPercent}%</td><td><Status value={p.commercial.status}/></td></tr>)}</tbody></table>{!products.length&&<p style={{padding:24}}>No hay referencias con estos filtros.</p>}</div>}
function ProductEditor({product,update}:{product:ReturnType<typeof adminRows>[number];update:(id:string,p:Override)=>void}){const c=product.commercial,r=product.calculated;return <aside className="product-editor"><div className="editor-head"><div><small>{product.sku}</small><h2>{product.name}</h2></div><Status value={c.status}/></div>{product.imageUrl&&<img className="admin-product-photo" src={product.imageUrl} alt={product.name}/>}<label>Publicación<select value={c.status} onChange={e=>update(product.id,{status:e.target.value as Override["status"]})}><option value="draft">Borrador</option><option value="quote">Bajo oferta</option><option value="ready">Publicable</option></select></label><div className="editor-grid"><MoneyField label="Coste de compra" value={c.cost} onChange={cost=>update(product.id,{cost})}/><MoneyField label="Coste de envío" value={c.inboundShipping} onChange={inboundShipping=>update(product.id,{inboundShipping})}/><MoneyField label="Manipulación" value={c.handling} onChange={handling=>update(product.id,{handling})}/><MoneyField label="Margen objetivo" value={c.targetMarginPercent} suffix="%" onChange={targetMarginPercent=>update(product.id,{targetMarginPercent})}/></div><div className="profit-box"><div><span>Coste puesto</span><b>{euro(r.landedCost)}</b></div><div><span>Precio de venta neto</span><b>{euro(r.salePriceNet)}</b></div><div><span>IVA incluido</span><b>{euro(r.salePriceVat)}</b></div><div className="profit"><span>Beneficio bruto</span><b>{euro(r.grossProfit)}</b></div></div><section className="supplier-box"><h3>Proveedor y referencia</h3><p><b>{product.supplier.name}</b><br/>{product.supplier.country} · {product.supplier.reference}</p><a href={product.sourceUrl} target="_blank" rel="noreferrer">Abrir fuente ↗</a><small>{c.costVerified?"Coste verificado":"⚠ Coste no verificado"}</small></section><section className="cert-box"><h3>Documentación</h3>{product.datasheetUrl?<a href={product.datasheetUrl} target="_blank" rel="noreferrer">Descargar ficha técnica ↗</a>:<span>Ficha técnica pendiente</span>}{product.certifications.map(x=><span key={x}>• {x}</span>)}</section></aside>}
function MoneyField({label,value,onChange,suffix="€"}:{label:string;value:number;onChange:(n:number)=>void;suffix?:string}){return <label>{label}<div><input type="number" min="0" step="0.01" value={value} onChange={e=>onChange(Number(e.target.value))}/><span>{suffix}</span></div></label>}
function adminRows(){return catalogProducts.map(product=>({...product,calculated:calculatePrice(product.commercial)}))}
function ProviderView(){const suppliers=Array.from(new Map(catalogProducts.map(p=>[p.supplier.name,p])).values());return <section className="simple-panel"><h2>Proveedores y referencias</h2>{suppliers.map(p=><article key={p.supplier.name}><div><b>{p.supplier.name}</b><span>{p.supplier.country}</span></div><span>{catalogProducts.filter(x=>x.supplier.name===p.supplier.name).length} referencias</span><a href={p.sourceUrl} target="_blank" rel="noreferrer">Revisar fuente ↗</a></article>)}</section>}
function InboxView(){return <section className="simple-panel inbox"><h2>Bandeja operativa</h2><p>Centro previsto para solicitudes de tienda, preestudios y consultas. La conexión real usará base de datos y Resend.</p>{[["OFERTA","Solicitud de línea de vida temporal"],["PREESTUDIO","Montaje de paneles en Madrid"],["PROVEEDOR","Pendiente tarifa profesional"]].map(([tag,title])=><article key={title}><span className="mail-tag">{tag}</span><div><b>{title}</b><small>Registro demostrativo</small></div><button>Abrir →</button></article>)}</section>}
