"use client";
import {useEffect,useMemo,useState} from "react";
import {catalogProducts,type CatalogProduct} from "@/data/catalog";
import {calculatePrice} from "@/lib/pricing";

type Override=Partial<Pick<CatalogProduct["commercial"],"cost"|"inboundShipping"|"handling"|"contingencyPercent"|"targetMarginPercent"|"status">>;
type Overrides=Record<string,Override>;
const storageKey="mp-admin-catalog-v1";
const euro=(n:number)=>n.toLocaleString("es-ES",{style:"currency",currency:"EUR"});

export default function CatalogAdmin(){
 const [tab,setTab]=useState<"catalogo"|"proveedores"|"bandeja">("catalogo");const [query,setQuery]=useState("");const [selectedId,setSelectedId]=useState(catalogProducts[0].id);const [overrides,setOverrides]=useState<Overrides>({});
 useEffect(()=>{try{setOverrides(JSON.parse(localStorage.getItem(storageKey)||"{}"))}catch{}},[]);
 const update=(id:string,patch:Override)=>setOverrides(current=>{const next={...current,[id]:{...current[id],...patch}};localStorage.setItem(storageKey,JSON.stringify(next));return next});
 const rows=useMemo(()=>catalogProducts.map(product=>({...product,commercial:{...product.commercial,...overrides[product.id]}})).map(product=>({...product,calculated:calculatePrice(product.commercial)})),[overrides]);
 const filtered=rows.filter(p=>`${p.sku} ${p.name} ${p.brand} ${p.family}`.toLowerCase().includes(query.toLowerCase()));const selected=rows.find(p=>p.id===selectedId)||rows[0];
 const ready=rows.filter(p=>p.commercial.status==="ready").length;const pending=rows.filter(p=>!p.commercial.costVerified).length;const projectedProfit=rows.reduce((sum,p)=>sum+p.calculated.grossProfit,0);
 return <div className="admin-shell"><aside className="admin-side"><a href="/" className="admin-brand"><b>MP</b><span>Administración<br/><small>COMERCIAL · LOCAL</small></span></a><nav><button className={tab==="catalogo"?"active":""} onClick={()=>setTab("catalogo")}>▦ Catálogo</button><button className={tab==="proveedores"?"active":""} onClick={()=>setTab("proveedores")}>⌂ Proveedores</button><button className={tab==="bandeja"?"active":""} onClick={()=>setTab("bandeja")}>✉ Bandeja operativa <i>3</i></button></nav><div className="admin-warning"><strong>ENTORNO LOCAL</strong><span>Sin autenticación ni base de datos. No publicar todavía.</span></div><a className="back-store" href="/tienda">← Ver tienda</a></aside>
 <main className="admin-main"><header><div><span className="admin-kicker">CENTRO DE CONTROL</span><h1>{tab==="catalogo"?"Catálogo y rentabilidad":tab==="proveedores"?"Proveedores y fuentes":"Bandeja operativa"}</h1></div><span className="admin-user">Administrador <b>A</b></span></header>
 {tab==="catalogo"&&<><section className="admin-stats"><Stat label="Referencias" value={String(rows.length)} note="catálogo inicial"/><Stat label="Listas para publicar" value={String(ready)} note="requieren validación"/><Stat label="Costes sin verificar" value={String(pending)} note="no vinculantes" alert/><Stat label="Beneficio unitario proyectado" value={euro(projectedProfit)} note="una unidad de cada SKU"/></section><section className="admin-work"><div className="admin-list"><div className="admin-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar SKU, producto o marca"/><button>+ Nuevo producto</button></div><div className="table-wrap"><table><thead><tr><th>Producto</th><th>Coste</th><th>Venta neta</th><th>Margen</th><th>Estado</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id} onClick={()=>setSelectedId(p.id)} className={selectedId===p.id?"selected":""}><td><b>{p.name}</b><small>{p.sku} · {p.family}</small></td><td>{euro(p.commercial.cost)}</td><td><b>{euro(p.calculated.salePriceNet)}</b></td><td>{p.calculated.actualMarginPercent}%</td><td><Status value={p.commercial.status}/></td></tr>)}</tbody></table></div></div><ProductEditor product={selected} update={update}/></section></>}
 {tab==="proveedores"&&<ProviderView/>}{tab==="bandeja"&&<InboxView/>}
 </main></div>;
}
function Stat({label,value,note,alert}:{label:string;value:string;note:string;alert?:boolean}){return <article className={alert?"alert":""}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Status({value}:{value:string}){return <span className={`status ${value}`}>{value==="ready"?"Publicable":value==="quote"?"Bajo oferta":"Borrador"}</span>}
function ProductEditor({product,update}:{product:ReturnType<typeof calculateRows>[number];update:(id:string,p:Override)=>void}){const c=product.commercial,r=product.calculated;return <aside className="product-editor"><div className="editor-head"><div><small>{product.sku}</small><h2>{product.name}</h2></div><Status value={c.status}/></div><label>Publicación<select value={c.status} onChange={e=>update(product.id,{status:e.target.value as Override["status"]})}><option value="draft">Borrador</option><option value="quote">Bajo oferta</option><option value="ready">Publicable</option></select></label><div className="editor-grid"><MoneyField label="Coste de compra" value={c.cost} onChange={cost=>update(product.id,{cost})}/><MoneyField label="Transporte entrada" value={c.inboundShipping} onChange={inboundShipping=>update(product.id,{inboundShipping})}/><MoneyField label="Manipulación" value={c.handling} onChange={handling=>update(product.id,{handling})}/><MoneyField label="Margen objetivo" value={c.targetMarginPercent} suffix="%" onChange={targetMarginPercent=>update(product.id,{targetMarginPercent})}/></div><div className="profit-box"><div><span>Coste puesto</span><b>{euro(r.landedCost)}</b></div><div><span>Precio de venta neto</span><b>{euro(r.salePriceNet)}</b></div><div><span>IVA incluido</span><b>{euro(r.salePriceVat)}</b></div><div className="profit"><span>Beneficio bruto</span><b>{euro(r.grossProfit)}</b></div></div><section className="supplier-box"><h3>Proveedor</h3><p><b>{product.supplier.name}</b><br/>{product.supplier.country} · Ref. {product.supplier.reference}</p><a href={product.sourceUrl} target="_blank" rel="noreferrer">Abrir fuente ↗</a><small>{c.costVerified?"Coste verificado":"⚠ Coste estimado: solicitar tarifa profesional"}</small></section><section className="cert-box"><h3>Documentación</h3>{product.certifications.map(x=><span key={x}>• {x}</span>)}</section></aside>}
function MoneyField({label,value,onChange,suffix="€"}:{label:string;value:number;onChange:(n:number)=>void;suffix?:string}){return <label>{label}<div><input type="number" min="0" step="0.01" value={value} onChange={e=>onChange(Number(e.target.value))}/><span>{suffix}</span></div></label>}
function calculateRows(){return catalogProducts.map(product=>({...product,calculated:calculatePrice(product.commercial)}))}
function ProviderView(){const suppliers=Array.from(new Map(catalogProducts.map(p=>[p.supplier.name,p])).values());return <section className="simple-panel"><h2>Proveedores y referencias</h2><p>Base de prospección. Ninguno figura como acuerdo activo hasta obtener tarifa, condiciones logísticas, permiso de catálogo y documentación.</p>{suppliers.map(p=><article key={p.supplier.name}><div><b>{p.supplier.name}</b><span>{p.supplier.country}</span></div><span>{catalogProducts.filter(x=>x.supplier.name===p.supplier.name).length} referencias</span><a href={p.sourceUrl} target="_blank" rel="noreferrer">Revisar fuente ↗</a></article>)}</section>}
function InboxView(){return <section className="simple-panel inbox"><h2>Bandeja operativa</h2><p>Centro unificado previsto para solicitudes de tienda, preestudios y consultas. Los mensajes mostrados son ejemplos; la conexión real usará la base de datos y Resend.</p>{[["OFERTA","Solicitud de línea de vida temporal","Cliente de ejemplo · Hoy, 09:42"],["PREESTUDIO","Montaje de paneles en Madrid","Referencia demostrativa · Ayer"],["PROVEEDOR","Pendiente tarifa profesional","Protección contra caídas · Hace 2 días"]].map(([tag,title,meta])=><article key={title}><span className="mail-tag">{tag}</span><div><b>{title}</b><small>{meta}</small></div><button>Abrir →</button></article>)}</section>}
