type RfqRow = {id: string; reference: string; company_name: string; contact_name: string; email: string; status: string; created_at: string};
const labels: Record<string, string> = {received: "Recibida", reviewing: "En revisión", supplier_pending: "Pendiente de proveedor", information_required: "Falta información", quoted: "Oferta enviada", closed: "Cerrada", cancelled: "Cancelada"};
export function OperationsDashboard({rfqs, configured}: {rfqs: RfqRow[]; configured: boolean}) {
  const open = rfqs.filter((rfq) => !["closed", "cancelled"].includes(rfq.status)).length;
  const reviewing = rfqs.filter((rfq) => rfq.status === "reviewing").length;
  const supplier = rfqs.filter((rfq) => rfq.status === "supplier_pending").length;
  return <div><div className="grid gap-4 sm:grid-cols-3"><Kpi label="Solicitudes abiertas" value={open} /><Kpi label="En revisión" value={reviewing} /><Kpi label="Esperando proveedor" value={supplier} /></div><section className="mt-8 overflow-hidden rounded-3xl border border-white/10 bg-neutral-900"><div className="flex items-center justify-between border-b border-white/10 p-6"><div><h2 className="text-xl font-black">Bandeja operativa</h2><p className="mt-1 text-sm text-neutral-400">La base de datos es la fuente de verdad.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${configured ? "bg-emerald-400/10 text-emerald-300" : "bg-orange-400/10 text-orange-200"}`}>{configured ? "Datos conectados" : "Pendiente de Supabase"}</span></div>{rfqs.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-neutral-500"><tr><th className="p-4">Expediente</th><th>Empresa</th><th>Contacto</th><th>Estado</th><th>Entrada</th></tr></thead><tbody>{rfqs.map((rfq) => <tr key={rfq.id} className="border-t border-white/5"><td className="p-4 font-bold text-yellow-300">{rfq.reference}</td><td>{rfq.company_name}</td><td><span className="block">{rfq.contact_name}</span><span className="text-xs text-neutral-500">{rfq.email}</span></td><td>{labels[rfq.status] ?? rfq.status}</td><td>{new Intl.DateTimeFormat("es-ES", {dateStyle: "short", timeStyle: "short"}).format(new Date(rfq.created_at))}</td></tr>)}</tbody></table></div> : <div className="p-10 text-center text-neutral-400">Todavía no hay solicitudes registradas.</div>}</section></div>;
}
function Kpi({label, value}: {label: string; value: number}) { return <div className="rounded-2xl border border-white/10 bg-neutral-900 p-5"><span className="text-sm text-neutral-400">{label}</span><strong className="mt-2 block text-4xl font-black">{value}</strong></div>; }
