"use client";

import {useEffect,useMemo, useState} from "react";
import Brand from "@/components/v21/Brand";
import {filterPublicCatalog,type PublicCatalogProduct} from "@/data/public-catalog";
import {SignInButton,SignedIn,SignedOut,UserButton} from "@clerk/nextjs";

const families = [
  ["todos","Todos"],["epi","Protección y EPI"],["corte","Corte y perforación"],["fijacion","Fijación"],
  ["sellado","Sellado y reparación"],["elevacion","Amarre y elevación"],["utiles","Útiles de montaje"],["altura","Trabajos en altura"],
] as const;
const prefabricatedMaterials=[["todos","Todos los prefabricados"],["hormigon","Hormigón"],["acero","Acero"],["madera","Madera"],["pvc","PVC"]] as const;

export default function MarketplaceMockup({initialProducts}:{initialProducts:PublicCatalogProduct[]}) {
  const [query,setQuery] = useState("");
  const [family,setFamily] = useState("todos");
  const [prefabricatedMaterial,setPrefabricatedMaterial] = useState("todos");
  const [cart,setCart] = useState<Record<string,number>>({});
  const [selected,setSelected] = useState<PublicCatalogProduct | null>(null);
  const [cartOpen,setCartOpen] = useState(false);
  const products = useMemo(()=>filterPublicCatalog(initialProducts,query,family,prefabricatedMaterial),[initialProducts,query,family,prefabricatedMaterial]);
  const units = Object.values(cart).reduce((sum,value)=>sum+value,0);
  const subtotal = initialProducts.reduce((sum,product)=>sum+(cart[product.id] ?? 0)*product.price,0);
  const add = (product:PublicCatalogProduct) => setCart((current)=>({...current,[product.id]:(current[product.id] ?? 0)+1}));
  useEffect(()=>{const id=decodeURIComponent(window.location.hash.slice(1));if(!id)return;const product=initialProducts.find(item=>item.id===id);if(product){setSelected(product);document.getElementById(id)?.scrollIntoView({block:"center"});}},[initialProducts]);
  return <div className="store-mock">
    <div className="demo-ribbon">CATÁLOGO EN PREPARACIÓN · PRECIOS CALCULADOS NO VINCULANTES · IVA NO INCLUIDO</div>
    <header className="commerce-head">
      <Brand />
      <form className="store-search" onSubmit={(event)=>event.preventDefault()}><label className="sr-only" htmlFor="store-search">Buscar productos</label><input id="store-search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar herramientas, EPI, fijaciones…"/><button aria-label="Buscar">⌕</button></form>
      <nav className="commerce-actions" aria-label="Cuenta y carrito"><SignedOut><SignInButton mode="modal"><button><small>Hola, identifícate</small><strong>Cuenta y listas</strong></button></SignInButton></SignedOut><SignedIn><span className="account-control"><UserButton/><strong>Mi cuenta</strong></span></SignedIn><button><small>Seguimiento</small><strong>Mis solicitudes</strong></button><button className="cart-trigger" onClick={()=>setCartOpen(true)}><span>{units}</span><strong>Carrito</strong></button></nav>
    </header>
    <nav className="category-bar" aria-label="Familias de producto">{families.map(([value,label])=><button key={value} className={family===value?"active":""} onClick={()=>setFamily(value)}>{label}</button>)}<a href="/#preestudio">Necesito ayuda técnica</a></nav>

    <main>
      <section className="store-hero"><div><span className="eyebrow">SUMINISTROS PARA MONTAJE PREFABRICADO</span><h1>Compra rápida.<br/><em>Criterio técnico.</em></h1><p>Material habitual de obra y productos configurables con asistencia especializada cuando la referencia exige comprobar carga, medida o compatibilidad.</p><div className="hero-pills"><span>Envío a obra</span><span>Documentación técnica</span><span>Oferta profesional</span></div></div><aside><span>¿No sabes qué referencia necesitas?</span><strong>Descríbenos la aplicación y la buscamos contigo.</strong><a href="/#preestudio">Solicitar selección técnica</a></aside></section>

      <section className="quick-categories" aria-label="Accesos rápidos"><CategoryTile code="01" title="Protección y EPI" note="Arneses y seguridad" onClick={()=>setFamily("epi")}/><CategoryTile code="02" title="Corte y perforación" note="Discos, brocas y abrasivos" onClick={()=>setFamily("corte")}/><CategoryTile code="03" title="Fijación y montaje" note="Anclajes, tornillería y útiles" onClick={()=>setFamily("fijacion")}/><CategoryTile code="04" title="Sellado y reparación" note="Adhesivos, juntas y morteros" onClick={()=>setFamily("sellado")}/></section>

       <section className="catalog-shell"><aside className="filters"><strong>Filtrar resultados</strong><label className="prefab-filter"><span>Tipo de prefabricado</span><select value={prefabricatedMaterial} onChange={event=>setPrefabricatedMaterial(event.target.value)}>{prefabricatedMaterials.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></aside>
        <div className="results"><div className="results-head"><div><span>{products.length} resultados con imagen verificada</span><h2>{family==="todos"?"Catálogo visual verificado":families.find(([value])=>value===family)?.[1]}</h2></div><label><span className="sr-only">Tipo de prefabricado</span><select aria-label="Tipo de prefabricado" value={prefabricatedMaterial} onChange={event=>setPrefabricatedMaterial(event.target.value)}>{prefabricatedMaterials.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><select aria-label="Ordenar resultados"><option>Más relevantes</option><option>Precio: menor a mayor</option><option>Mejor valorados</option></select></div><div className="catalog-help"><div><span className="eyebrow">BÚSQUEDA ASISTIDA</span><h3>¿No encuentras lo que buscas?</h3><p>Dinos la pieza, aplicación o problema de montaje. Te lo buscamos y, si hace falta, lo revisamos contigo por teléfono.</p></div><a href="/?producto=busqueda-asistida#preestudio">Te lo buscamos →</a></div><div className="product-grid">{products.map((product)=><ProductCard key={product.id} product={product} onAdd={()=>add(product)} onOpen={()=>setSelected(product)}/>)}</div>{!products.length&&<div className="empty-state"><strong>No hay todavía fichas visuales verificadas para este filtro</strong><span>Prueba otro filtro o utiliza la búsqueda asistida y localizaremos la referencia.</span></div>}</div>
      </section>
    </main>
    <nav className="mobile-dock" aria-label="Navegación móvil"><button onClick={()=>setFamily("todos")}>⌂<span>Inicio</span></button><button onClick={()=>document.getElementById("store-search")?.focus()}>⌕<span>Buscar</span></button><button>◎<span>Cuenta</span></button><button onClick={()=>setCartOpen(true)} className="dock-cart">▣<b>{units}</b><span>Carrito</span></button></nav>
    {selected&&<ProductPanel product={selected} onClose={()=>setSelected(null)} onAdd={()=>{add(selected);setSelected(null);}}/>}
    {cartOpen&&<CartPanel products={initialProducts} cart={cart} subtotal={subtotal} onClose={()=>setCartOpen(false)} onChange={(id,amount)=>setCart((current)=>({...current,[id]:Math.max(0,amount)}))}/>} 
  </div>;
}

function CategoryTile({code,title,note,onClick}:{code:string;title:string;note:string;onClick:()=>void}){return <button className="category-tile" onClick={onClick}><span>{code}</span><strong>{title}</strong><small>{note}</small></button>}
function ProductVisual({product,imageUrl}:{product:PublicCatalogProduct;imageUrl?:string}){const photo=imageUrl??product.imageUrl;return <div className={`product-visual ${photo?"has-photo":""}`} style={{"--accent":product.accent} as React.CSSProperties}>{photo?<img src={photo} alt={product.name}/>:<><span>{product.initials}</span><small>FOTO EN BÚSQUEDA</small></>}</div>}
const euros=(value:number)=>`${value.toFixed(2).replace(".",",")} €`;
function ProductCard({product,onAdd,onOpen}:{product:PublicCatalogProduct;onAdd:()=>void;onOpen:()=>void}){const ready=product.purchasable;return <article className="product-card" id={product.id}><button className="visual-button" onClick={onOpen} aria-label={`Ver ${product.name}`}><ProductVisual product={product}/></button><div className="product-info"><small className="brand-line">{product.brand} · {product.family}</small><button className="product-name" onClick={onOpen}>{product.name}</button><div className="price-line">{ready?<><span><small>Precio sin IVA</small><strong>{euros(product.price)}</strong></span><small>/ {product.unit}</small></>:<strong>Solicitar oferta</strong>}</div>{ready&&<small className="tax-summary">IVA ({product.vatPercent} %): {euros(product.priceVat-product.price)} · Total con IVA: {euros(product.priceVat)}</small>}<span className="delivery-public">Transporte: calculado según destino</span><span className="availability">{ready?product.availability:"Configuración técnica necesaria"}</span><button className="add-button" onClick={ready?onAdd:onOpen}>{ready?"Añadir al carrito":"Solicitar oferta"}</button></div></article>}
function ProductPanel({product,onClose,onAdd}:{product:PublicCatalogProduct;onClose:()=>void;onAdd:()=>void}){const ready=product.purchasable;const [activeImage,setActiveImage]=useState(product.imageUrls?.[0]??product.imageUrl);return <div className="overlay" role="presentation" onMouseDown={onClose}><section className="product-panel" role="dialog" aria-modal="true" aria-label={product.name} onMouseDown={(event)=>event.stopPropagation()}><button className="close" onClick={onClose}>×</button><div className="product-gallery"><ProductVisual product={product} imageUrl={activeImage}/><div className="gallery-thumbs">{product.imageUrls?.map((url,index)=><button key={url} className={url===activeImage?"active":""} onClick={()=>setActiveImage(url)} aria-label={`Ver imagen ${index+1}`}><img src={url} alt=""/></button>)}</div></div><div><small>{product.brand} · {product.family} · {product.sku}</small><h2>{product.name}</h2><p>{product.description}</p><ul>{product.specifications.map(item=><li key={item}>{item}</li>)}<li>Aplicaciones: {product.segments.join(" · ")}</li></ul>{product.datasheetUrl&&<a href={product.datasheetUrl} target="_blank" rel="noreferrer">Abrir documentación técnica ↗</a>}<div className="buy-box">{ready?<><div><span>Precio sin IVA</span><strong>{euros(product.price)}</strong></div><div><span>IVA ({product.vatPercent} %)</span><b>{euros(product.priceVat-product.price)}</b></div><div><span>Total con IVA</span><b>{euros(product.priceVat)}</b></div><span>Transporte: calculado según destino antes de confirmar el pedido.</span><button onClick={onAdd}>Añadir al carrito</button></>:<><strong>Solicitar oferta</strong><span>Precio y transporte según configuración y destino.</span><a className="add-button" href={`/?producto=${encodeURIComponent(product.id)}#preestudio`}>Solicitar información</a></>}</div></div></section></div>}
function CartPanel({products,cart,subtotal,onClose,onChange}:{products:PublicCatalogProduct[];cart:Record<string,number>;subtotal:number;onClose:()=>void;onChange:(id:string,amount:number)=>void}){const lines=products.filter((product)=>cart[product.id]>0);return <div className="overlay cart-overlay" role="presentation" onMouseDown={onClose}><aside className="cart-panel" role="dialog" aria-modal="true" aria-label="Carrito" onMouseDown={(event)=>event.stopPropagation()}><button className="close" onClick={onClose}>×</button><span className="eyebrow">TU SELECCIÓN</span><h2>Carrito</h2>{lines.length? <><div className="cart-lines">{lines.map((product)=><div className="cart-line" key={product.id}><ProductVisual product={product}/><div><strong>{product.name}</strong><small>{product.price.toFixed(2).replace(".",",")} € / {product.unit}</small><div><button onClick={()=>onChange(product.id,cart[product.id]-1)}>−</button><span>{cart[product.id]}</span><button onClick={()=>onChange(product.id,cart[product.id]+1)}>+</button></div></div></div>)}</div><div className="subtotal"><span>Subtotal sin IVA</span><strong>{subtotal.toFixed(2).replace(".",",")} €</strong></div><button className="checkout-demo">Solicitar oferta</button><p>No se realizará ningún pago. Confirmaremos referencias, stock y transporte antes de emitir una oferta vinculante.</p></>:<div className="empty-cart"><strong>Tu carrito está vacío</strong><span>Añade productos para probar el recorrido.</span></div>}</aside></div>}
