"use client";
import {useState} from "react";
import FileUploader from "@/components/prestudy/FileUploader";
import type {PublicCatalogProduct} from "@/data/public-catalog";
import type {ProductInquiryKind,ProductInquiryInput} from "@/lib/product-inquiry";
import type {UploadedDocument} from "@/lib/prestudy";

export default function ProductInquiryPanel({kind,product,onClose}:{kind:ProductInquiryKind;product?:PublicCatalogProduct;onClose:()=>void}){
 const [documents,setDocuments]=useState<UploadedDocument[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [reference,setReference]=useState("");
 const title=kind==="datasheet"?"Solicitar ficha técnica":kind==="search"?"Cuéntanos qué producto necesitas":"Solicitar información y oferta";
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const body:ProductInquiryInput={kind,productId:product?.id??"",productName:product?.name??"",name:String(form.get("name")??""),company:String(form.get("company")??""),email:String(form.get("email")??""),phone:String(form.get("phone")??""),message:String(form.get("message")??""),documents,consent:form.get("consent")==="on",website:String(form.get("website")??"")};try{const response=await fetch("/api/product-inquiries",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo enviar la solicitud.");setReference(result.reference);}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo enviar la solicitud.");}finally{setBusy(false);}}
 return <div className="overlay inquiry-overlay" role="presentation" onClick={event=>{if(event.target===event.currentTarget)onClose();}}><section className="inquiry-panel" role="dialog" aria-modal="true" aria-label={title}><header><span>SOLICITUD DE PRODUCTO</span><h2>{title}</h2><button className="close" onClick={onClose} aria-label="Cerrar">×</button></header>{reference?<div className="inquiry-success"><strong>Solicitud recibida</strong><p>La hemos registrado con la referencia <b>{reference}</b>. Podremos identificar qué has pedido y responderte por los datos de contacto indicados.</p><button onClick={onClose}>Cerrar</button></div>:<form onSubmit={submit}>{product&&<div className="inquiry-product"><img src={product.imageUrl} alt=""/><div><small>{product.sku} · {product.brand}</small><strong>{product.name}</strong></div></div>}<p>{kind==="search"?"Indica la pieza, aplicación, medidas o carga. Puedes adjuntar una foto, plano o ficha de referencia.":kind==="datasheet"?"Solicitaremos al proveedor la documentación exacta de esta referencia y te la enviaremos. Así evitamos entregar una ficha genérica o incorrecta.":"Indica cantidad, medida o capacidad necesaria y código postal de entrega. Te responderemos con referencia, plazo, transporte y precio."}</p><div className="inquiry-grid"><label>Nombre *<input name="name" required/></label><label>Empresa<input name="company"/></label><label>Email<input name="email" type="email"/></label><label>Teléfono<input name="phone" type="tel"/></label></div><label>Qué necesitas *<textarea name="message" required minLength={10} rows={5} placeholder="Cantidad, medida/capacidad, aplicación, lugar de entrega y cualquier requisito técnico…"/></label><fieldset><legend>Fotos, planos o documentos</legend><FileUploader documents={documents} onChange={setDocuments}/></fieldset><input className="hp" name="website" tabIndex={-1} autoComplete="off"/><label className="consent"><input type="checkbox" name="consent" required/> Autorizo el tratamiento de estos datos para atender esta solicitud.</label>{error&&<p className="field-error" role="alert">{error}</p>}<button className="inquiry-submit" disabled={busy}>{busy?"Enviando…":"Enviar solicitud"}</button><small className="inquiry-contact">También puedes llamar al <a href="tel:+34624473123">+34 624 473 123</a> o escribir a <a href="mailto:ofertas@montajedeprefabricados.com">ofertas@montajedeprefabricados.com</a>.</small></form>}</section></div>;
}
